name: MultiVersion
api: 5.27.1
main: AzliRynz\MultiVersion-NG\Loader
version: 1.0.0
description: A plugin to allows older Minecraft client versions to connect to newer server versions.
mcpe-protocol: 786
authors: [AkmalFairuz, AzliRynz]
permissions:
  multiversion.command:
    default: op
